[package]
name = "hog_and_svm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
linfa = "0.7.0"
linfa-svm = "0.7.0"
ndarray = "0.15.6"
rand = "0.8.5"
